/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalFuzzyLanguageParser;
import org.xtext.example.mydsl.services.FuzzyLanguageGrammarAccess;

public class FuzzyLanguageParser extends AbstractAntlrParser {

	@Inject
	private FuzzyLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFuzzyLanguageParser createParser(XtextTokenStream stream) {
		return new InternalFuzzyLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FuzzyModel";
	}

	public FuzzyLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FuzzyLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
