/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.fuzzyLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface FuzzyLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fuzzyLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/FuzzyLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fuzzyLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FuzzyLanguagePackage eINSTANCE = org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyModelImpl <em>Fuzzy Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyModelImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getFuzzyModel()
   * @generated
   */
  int FUZZY_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUZZY_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Fuzzy Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUZZY_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.OutputsImpl <em>Outputs</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.OutputsImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getOutputs()
   * @generated
   */
  int OUTPUTS = 1;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUTS__OUT = 0;

  /**
   * The feature id for the '<em><b>Wr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUTS__WR = 1;

  /**
   * The number of structural features of the '<em>Outputs</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.WriteImpl <em>Write</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.WriteImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getWrite()
   * @generated
   */
  int WRITE = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Write</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.OutputImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__PATH = 1;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzySystemBuildingImpl <em>Fuzzy System Building</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzySystemBuildingImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getFuzzySystemBuilding()
   * @generated
   */
  int FUZZY_SYSTEM_BUILDING = 4;

  /**
   * The feature id for the '<em><b>Affectations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUZZY_SYSTEM_BUILDING__AFFECTATIONS = 0;

  /**
   * The number of structural features of the '<em>Fuzzy System Building</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUZZY_SYSTEM_BUILDING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.AffectationImpl <em>Affectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.AffectationImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getAffectation()
   * @generated
   */
  int AFFECTATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__VALUE = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__PARAMS = 2;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__EXP = 3;

  /**
   * The number of structural features of the '<em>Affectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPS = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VALUE = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.BindingImpl <em>Binding</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.BindingImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getBinding()
   * @generated
   */
  int BINDING = 7;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__OP = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__TARGET = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__PARAMS = 2;

  /**
   * The number of structural features of the '<em>Binding</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.ParamImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getParam()
   * @generated
   */
  int PARAM = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__VALUE = 0;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.TypeSetImpl <em>Type Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.TypeSetImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getTypeSet()
   * @generated
   */
  int TYPE_SET = 9;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_SET__TYPE_NAME = 0;

  /**
   * The number of structural features of the '<em>Type Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_SET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyConfigImpl <em>Fuzzy Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyConfigImpl
   * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getFuzzyConfig()
   * @generated
   */
  int FUZZY_CONFIG = 10;

  /**
   * The feature id for the '<em><b>Type SET</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUZZY_CONFIG__TYPE_SET = 0;

  /**
   * The feature id for the '<em><b>Bindings List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUZZY_CONFIG__BINDINGS_LIST = 1;

  /**
   * The number of structural features of the '<em>Fuzzy Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUZZY_CONFIG_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyModel <em>Fuzzy Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fuzzy Model</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyModel
   * @generated
   */
  EClass getFuzzyModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyModel#getElements()
   * @see #getFuzzyModel()
   * @generated
   */
  EReference getFuzzyModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.Outputs <em>Outputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outputs</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Outputs
   * @generated
   */
  EClass getOutputs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.fuzzyLanguage.Outputs#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Out</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Outputs#getOut()
   * @see #getOutputs()
   * @generated
   */
  EReference getOutputs_Out();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.fuzzyLanguage.Outputs#getWr <em>Wr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Wr</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Outputs#getWr()
   * @see #getOutputs()
   * @generated
   */
  EReference getOutputs_Wr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.Write <em>Write</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Write</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Write
   * @generated
   */
  EClass getWrite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Write#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Write#getValue()
   * @see #getWrite()
   * @generated
   */
  EAttribute getWrite_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Output#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Output#getType()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Output#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Output#getPath()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzySystemBuilding <em>Fuzzy System Building</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fuzzy System Building</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzySystemBuilding
   * @generated
   */
  EClass getFuzzySystemBuilding();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzySystemBuilding#getAffectations <em>Affectations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Affectations</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzySystemBuilding#getAffectations()
   * @see #getFuzzySystemBuilding()
   * @generated
   */
  EReference getFuzzySystemBuilding_Affectations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.Affectation <em>Affectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affectation</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Affectation
   * @generated
   */
  EClass getAffectation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Affectation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Affectation#getName()
   * @see #getAffectation()
   * @generated
   */
  EAttribute getAffectation_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Affectation#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Affectation#getValue()
   * @see #getAffectation()
   * @generated
   */
  EAttribute getAffectation_Value();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.fuzzyLanguage.Affectation#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Affectation#getParams()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Params();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.fuzzyLanguage.Affectation#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Affectation#getExp()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.fuzzyLanguage.Expression#getExps <em>Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exps</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Expression#getExps()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Exps();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.fuzzyLanguage.Expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Expression#getValue()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.Binding <em>Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binding</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Binding
   * @generated
   */
  EClass getBinding();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Binding#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Binding#getOp()
   * @see #getBinding()
   * @generated
   */
  EAttribute getBinding_Op();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Binding#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Binding#getTarget()
   * @see #getBinding()
   * @generated
   */
  EAttribute getBinding_Target();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.fuzzyLanguage.Binding#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Binding#getParams()
   * @see #getBinding()
   * @generated
   */
  EReference getBinding_Params();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.Param#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.Param#getValue()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.TypeSet <em>Type Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Set</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.TypeSet
   * @generated
   */
  EClass getTypeSet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.fuzzyLanguage.TypeSet#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Name</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.TypeSet#getTypeName()
   * @see #getTypeSet()
   * @generated
   */
  EAttribute getTypeSet_TypeName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig <em>Fuzzy Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fuzzy Config</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig
   * @generated
   */
  EClass getFuzzyConfig();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig#getTypeSET <em>Type SET</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type SET</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig#getTypeSET()
   * @see #getFuzzyConfig()
   * @generated
   */
  EReference getFuzzyConfig_TypeSET();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig#getBindingsList <em>Bindings List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Bindings List</em>'.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig#getBindingsList()
   * @see #getFuzzyConfig()
   * @generated
   */
  EReference getFuzzyConfig_BindingsList();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FuzzyLanguageFactory getFuzzyLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyModelImpl <em>Fuzzy Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyModelImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getFuzzyModel()
     * @generated
     */
    EClass FUZZY_MODEL = eINSTANCE.getFuzzyModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUZZY_MODEL__ELEMENTS = eINSTANCE.getFuzzyModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.OutputsImpl <em>Outputs</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.OutputsImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getOutputs()
     * @generated
     */
    EClass OUTPUTS = eINSTANCE.getOutputs();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTPUTS__OUT = eINSTANCE.getOutputs_Out();

    /**
     * The meta object literal for the '<em><b>Wr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTPUTS__WR = eINSTANCE.getOutputs_Wr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.WriteImpl <em>Write</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.WriteImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getWrite()
     * @generated
     */
    EClass WRITE = eINSTANCE.getWrite();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE__VALUE = eINSTANCE.getWrite_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.OutputImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__TYPE = eINSTANCE.getOutput_Type();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__PATH = eINSTANCE.getOutput_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzySystemBuildingImpl <em>Fuzzy System Building</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzySystemBuildingImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getFuzzySystemBuilding()
     * @generated
     */
    EClass FUZZY_SYSTEM_BUILDING = eINSTANCE.getFuzzySystemBuilding();

    /**
     * The meta object literal for the '<em><b>Affectations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUZZY_SYSTEM_BUILDING__AFFECTATIONS = eINSTANCE.getFuzzySystemBuilding_Affectations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.AffectationImpl <em>Affectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.AffectationImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getAffectation()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAffectation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AFFECTATION__NAME = eINSTANCE.getAffectation_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AFFECTATION__VALUE = eINSTANCE.getAffectation_Value();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__PARAMS = eINSTANCE.getAffectation_Params();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__EXP = eINSTANCE.getAffectation_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

    /**
     * The meta object literal for the '<em><b>Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPS = eINSTANCE.getExpression_Exps();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__VALUE = eINSTANCE.getExpression_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.BindingImpl <em>Binding</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.BindingImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getBinding()
     * @generated
     */
    EClass BINDING = eINSTANCE.getBinding();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINDING__OP = eINSTANCE.getBinding_Op();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINDING__TARGET = eINSTANCE.getBinding_Target();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING__PARAMS = eINSTANCE.getBinding_Params();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.ParamImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__VALUE = eINSTANCE.getParam_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.TypeSetImpl <em>Type Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.TypeSetImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getTypeSet()
     * @generated
     */
    EClass TYPE_SET = eINSTANCE.getTypeSet();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_SET__TYPE_NAME = eINSTANCE.getTypeSet_TypeName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyConfigImpl <em>Fuzzy Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyConfigImpl
     * @see org.xtext.example.mydsl.fuzzyLanguage.impl.FuzzyLanguagePackageImpl#getFuzzyConfig()
     * @generated
     */
    EClass FUZZY_CONFIG = eINSTANCE.getFuzzyConfig();

    /**
     * The meta object literal for the '<em><b>Type SET</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUZZY_CONFIG__TYPE_SET = eINSTANCE.getFuzzyConfig_TypeSET();

    /**
     * The meta object literal for the '<em><b>Bindings List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUZZY_CONFIG__BINDINGS_LIST = eINSTANCE.getFuzzyConfig_BindingsList();

  }

} //FuzzyLanguagePackage
