/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.fuzzyLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fuzzy Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig#getTypeSET <em>Type SET</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig#getBindingsList <em>Bindings List</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyLanguagePackage#getFuzzyConfig()
 * @model
 * @generated
 */
public interface FuzzyConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Type SET</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type SET</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type SET</em>' containment reference.
   * @see #setTypeSET(TypeSet)
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyLanguagePackage#getFuzzyConfig_TypeSET()
   * @model containment="true"
   * @generated
   */
  TypeSet getTypeSET();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fuzzyLanguage.FuzzyConfig#getTypeSET <em>Type SET</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type SET</em>' containment reference.
   * @see #getTypeSET()
   * @generated
   */
  void setTypeSET(TypeSet value);

  /**
   * Returns the value of the '<em><b>Bindings List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.fuzzyLanguage.Binding}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bindings List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bindings List</em>' containment reference list.
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyLanguagePackage#getFuzzyConfig_BindingsList()
   * @model containment="true"
   * @generated
   */
  EList<Binding> getBindingsList();

} // FuzzyConfig
