/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.fuzzyLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outputs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.fuzzyLanguage.Outputs#getOut <em>Out</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.fuzzyLanguage.Outputs#getWr <em>Wr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyLanguagePackage#getOutputs()
 * @model
 * @generated
 */
public interface Outputs extends EObject
{
  /**
   * Returns the value of the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Out</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out</em>' containment reference.
   * @see #setOut(Output)
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyLanguagePackage#getOutputs_Out()
   * @model containment="true"
   * @generated
   */
  Output getOut();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fuzzyLanguage.Outputs#getOut <em>Out</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out</em>' containment reference.
   * @see #getOut()
   * @generated
   */
  void setOut(Output value);

  /**
   * Returns the value of the '<em><b>Wr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Wr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wr</em>' containment reference.
   * @see #setWr(Write)
   * @see org.xtext.example.mydsl.fuzzyLanguage.FuzzyLanguagePackage#getOutputs_Wr()
   * @model containment="true"
   * @generated
   */
  Write getWr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.fuzzyLanguage.Outputs#getWr <em>Wr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wr</em>' containment reference.
   * @see #getWr()
   * @generated
   */
  void setWr(Write value);

} // Outputs
