/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractFuzzyLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FuzzyLanguageIdeModule extends AbstractFuzzyLanguageIdeModule {
}
